apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=8062a465cf5f8865a591f8cc01c80f471d4dc090

namespace: release-service
